import { Question } from './types';

export const QUESTIONS: Question[] = [
  { id: 1, category: 0, text: 'Which three levels make up the diversity of nature?', options: ['Climate, water and soil', 'Genes, species and ecosystems', 'Plants, animals and fungi', 'Local, regional and global'], correctIndex: 1, explanation: 'Natural diversity is assessed at three connected levels: genetic diversity within species, species diversity and ecosystem diversity.' },
  { id: 2, category: 0, text: 'An endemic species is one that…', options: ['Only lives at night', 'Occurs naturally within a limited area', 'Has been introduced by people', 'Is abundant worldwide'], correctIndex: 1, explanation: 'Endemic species have a naturally restricted distribution. That limitation can make them more vulnerable to local change.' },
  { id: 3, category: 0, text: 'Why can genetic diversity make a population more resilient?', options: ['It removes all competition', 'It increases the chance that some individuals can tolerate change', 'It prevents every disease', 'It makes all species identical'], correctIndex: 1, explanation: 'A genetically diverse population has a wider range of possible responses to disease, climate variation and other pressures.' },
  { id: 4, category: 0, text: 'Which ecological function is performed by many insects, birds and bats?', options: ['Compacting soil', 'Pollinating plants', 'Increasing light pollution', 'Creating invasive species'], correctIndex: 1, explanation: 'Pollination enables many wild plants and crops to reproduce and supports entire food webs.' },
  { id: 5, category: 0, text: 'What is the key difference between a non-native and an invasive species?', options: ['There is no difference', 'An invasive species causes impacts as it establishes and spreads', 'A non-native species is always poisonous', 'An invasive species only lives in cities'], correctIndex: 1, explanation: 'Not every introduced species is invasive. It becomes invasive when its spread causes ecological, economic or social harm.' },
  { id: 6, category: 0, text: 'Before work starts during the breeding season, which action provides the best information?', options: ['Start work and observe later', 'Carry out an ecological survey first', 'Increase the lighting', 'Remove all vegetation'], correctIndex: 1, explanation: 'A pre-work survey can identify nests, shelters or sensitive species so that timing, design and preventive measures can be adapted.' },
  { id: 7, category: 0, text: 'Why can artificial light at night affect wildlife?', options: ['It improves every habitat', 'It alters orientation, activity and biological cycles', 'It reduces noise', 'It increases genetic diversity'], correctIndex: 1, explanation: 'Artificial light can change movement, feeding, reproduction and predator–prey relationships. Its need, direction and duration should be controlled.' },
  { id: 8, category: 0, text: 'What can happen when a keystone species disappears from a food web?', options: ['Nothing, because every species is interchangeable', 'Cascading effects across other populations', 'Only the visual landscape changes', 'Stability automatically increases'], correctIndex: 1, explanation: 'Ecological relationships connect species. Losing a keystone species can alter abundance, habitats and ecosystem functions.' },

  { id: 101, category: 1, text: 'What are ecosystem services?', options: ['Gardening services', 'Contributions that ecosystems make to human wellbeing and activity', 'Agricultural products only', 'Protected areas only'], correctIndex: 1, explanation: 'They include provisioning, regulating and cultural contributions, together with the ecological processes that support them. Organisations depend on these services directly and indirectly.' },
  { id: 102, category: 1, text: 'Which service can a healthy wetland provide?', options: ['Increasing erosion', 'Regulating floods and filtering water', 'Removing every species', 'Preventing all droughts'], correctIndex: 1, explanation: 'Wetlands store water, retain sediment and nutrients, and provide habitat. They do not remove all risk, but they can reduce it.' },
  { id: 103, category: 1, text: 'What does ecological connectivity mean?', options: ['Providing Wi-Fi in the countryside', 'Allowing organisms to move between habitats', 'Connecting buildings with roads', 'Concentrating wildlife in one enclosure'], correctIndex: 1, explanation: 'Connectivity supports dispersal, migration and genetic exchange. Corridors and wildlife crossings reduce isolation.' },
  { id: 104, category: 1, text: 'Healthy soil should be understood as…', options: ['An inert support', 'A living system that regulates water, nutrients and carbon', 'A construction waste product', 'A surface that should always be sealed'], correctIndex: 1, explanation: 'Soil contains living organisms, stores carbon, filters water and supports vegetation. Sealing or contaminating it reduces those functions.' },
  { id: 105, category: 1, text: 'What is a common consequence of habitat fragmentation?', options: ['Improved movement for every species', 'Isolated populations and stronger edge effects', 'No need for monitoring', 'An automatic increase in diversity'], correctIndex: 1, explanation: 'Fragmentation divides continuous areas into patches, obstructs movement and exposes more habitat to noise, light, predation and other pressures.' },
  { id: 106, category: 1, text: 'What is the purpose of an ecological baseline?', options: ['To justify a decision already made', 'To establish the starting condition and compare change', 'To replace monitoring', 'To measure emissions only'], correctIndex: 1, explanation: 'A baseline describes the initial condition using clear methods and boundaries. Without it, attributing improvement or deterioration to an action is difficult.' },
  { id: 107, category: 1, text: 'What characterises a nature-based solution?', options: ['Using the colour green', 'Addressing a societal challenge while protecting or restoring ecosystems', 'Planting trees anywhere', 'Replacing every type of infrastructure'], correctIndex: 1, explanation: 'A nature-based solution must address a real challenge and deliver verifiable ecological benefits through a design suited to the local context.' },
  { id: 108, category: 1, text: 'Why does landscape scale matter?', options: ['A site is never connected to its surroundings', 'Water, species and pressures cross a facility boundary', 'Only national maps are relevant', 'It removes the need to consult local stakeholders'], correctIndex: 1, explanation: 'Ecological processes do not follow administrative boundaries. Considering catchments, corridors and neighbouring land uses improves decisions.' },

  { id: 201, category: 2, text: 'What is the difference between a nature impact and a nature dependency?', options: ['They are synonyms', 'An impact is a change caused; a dependency is something the activity needs', 'A dependency is always positive', 'Impacts only occur outside the company'], correctIndex: 1, explanation: 'An activity can affect nature while also depending on water, climate regulation, materials or soil stability.' },
  { id: 202, category: 2, text: 'Which approach identifies impacts from raw materials through to end of life?', options: ['Life-cycle thinking', 'A single visual inspection', 'Environmental marketing', 'Isolated financial accounting'], correctIndex: 0, explanation: 'Life-cycle thinking helps prevent shifting impacts between stages or locations and allows alternatives to be compared using consistent boundaries.' },
  { id: 203, category: 2, text: 'Which pressure is commonly associated with soil sealing?', options: ['Loss of infiltration and habitat', 'Greater ecological connectivity', 'Automatic soil recovery', 'Less runoff in every case'], correctIndex: 0, explanation: 'Impermeable surfaces reduce infiltration, alter drainage and remove soil functions. Avoiding and minimising the occupied area is therefore a priority.' },
  { id: 204, category: 2, text: 'Which combination is most useful when assessing water-related risk at a facility?', options: ['Annual consumption only', 'Consumption, catchment condition and the needs of other users', 'Water price only', 'The number of taps'], correctIndex: 1, explanation: 'The same level of consumption can have very different implications depending on availability, quality, seasonality and competition within the catchment.' },
  { id: 205, category: 2, text: 'What improves the environmental traceability of a purchase?', options: ['Knowing the origin, material, supplier and supporting evidence', 'Using a green label with no criteria', 'Always choosing the cheapest option', 'Avoiding questions to the supplier'], correctIndex: 0, explanation: 'Traceability helps locate risks in the value chain and verify requirements, certifications and improvement plans.' },
  { id: 206, category: 2, text: 'Which is a nature-related physical risk?', options: ['Water scarcity interrupting operations', 'Changing a logo', 'An internal campaign', 'A communications award'], correctIndex: 0, explanation: 'Ecosystem degradation can intensify drought, flooding, erosion and material shortages, affecting operational continuity.' },
  { id: 207, category: 2, text: 'A spilled substance can affect an ecosystem mainly through…', options: ['Its exposure pathway, concentration and persistence', 'The colour of its container', 'The age of the building', 'The number of meetings held'], correctIndex: 0, explanation: 'Assessment should follow the route from source to receptor: drains, soil, surface water, groundwater and exposed organisms.' },
  { id: 208, category: 2, text: 'What is the risk of looking only at the organisation’s own site?', options: ['There is no risk', 'Missing relevant impacts from suppliers, logistics and materials', 'Measuring too much', 'Always reducing costs'], correctIndex: 1, explanation: 'A significant share of the footprint may sit in the value chain. It should be prioritised according to materiality, influence and data quality.' },

  { id: 301, category: 3, text: 'What is the correct order of the mitigation hierarchy?', options: ['Offset, restore, minimise, avoid', 'Avoid, minimise, restore and, only then, offset', 'Restore, avoid, offset, minimise', 'Measure, communicate, offset, close'], correctIndex: 1, explanation: 'First avoid the impact; then minimise what is unavoidable, restore what has been affected and consider compensation only for residual impacts.' },
  { id: 302, category: 3, text: 'Why is offsetting not a substitute for avoidance?', options: ['Because it always costs less', 'Because some natural values are irreplaceable or take decades to recover', 'Because it requires no monitoring', 'Because it removes the need for design'], correctIndex: 1, explanation: 'Offsets involve uncertainty, time lags and ecological limits. They do not justify destroying a critical value that could have been retained.' },
  { id: 303, category: 3, text: 'Which measure best applies the principle of avoidance?', options: ['Relocating work away from a sensitive habitat', 'Planting after construction', 'Paying for a campaign', 'Measuring the damage at the end'], correctIndex: 0, explanation: 'Changing location, design or timing before an impact occurs is generally more effective and reliable than repairing damage afterwards.' },
  { id: 304, category: 3, text: 'What does a robust restoration plan need?', options: ['A plant list only', 'An objective, ecological reference, actions, indicators and maintenance', 'A photograph from day one', 'A promise without a deadline'], correctIndex: 1, explanation: 'Restoration aims to recover ecological structure, functions and trajectory. It requires measurable objectives and management over an appropriate period.' },
  { id: 305, category: 3, text: 'To reduce the impact of outdoor lighting, what should be asked first?', options: ['Can we install more lights?', 'Is the lighting needed, where and for how long?', 'Which colour looks best?', 'Can it be seen from far away?'], correctIndex: 1, explanation: 'The sequence is to avoid unnecessary lighting and then limit intensity, duration, direction and spectrum according to sensitive receptors.' },
  { id: 306, category: 3, text: 'What is adaptive management?', options: ['Keeping the plan even when it fails', 'Adjusting measures in response to monitoring results', 'Changing objectives every week', 'Acting without indicators'], correctIndex: 1, explanation: 'Thresholds and responses are defined before implementation. Monitoring data are then used to correct measures that are not delivering the intended result.' },
  { id: 307, category: 3, text: 'Which criterion helps prevent unsuitable planting during restoration?', options: ['Using native species suited to the site', 'Choosing only the fastest-growing species', 'Buying the cheapest seed mix', 'Using any ornamental species'], correctIndex: 0, explanation: 'Origin, diversity and suitability to local soil and climate matter. Invasive-species risk and maintenance capacity must also be considered.' },
  { id: 308, category: 3, text: 'What does additionality mean for an offsetting measure?', options: ['The result would have happened anyway', 'It delivers an improvement that would not occur without the intervention', 'It needs no evidence', 'It only adds budget'], correctIndex: 1, explanation: 'An additional measure delivers a result beyond existing duties and trends and must be demonstrated against a credible reference.' },

  { id: 401, category: 4, text: 'Which of these is a state indicator?', options: ['Area of land occupied', 'Ecological condition of a wetland', 'Number of meetings', 'Budget allocated'], correctIndex: 1, explanation: 'State indicators describe the condition of nature. Land occupied is a pressure, while actions delivered are response indicators.' },
  { id: 402, category: 4, text: 'What makes an indicator useful for decision-making?', options: ['It is easy to publish', 'It is relevant, measurable, comparable and linked to an objective', 'It always increases', 'It has no unit'], correctIndex: 1, explanation: 'A useful indicator has a definition, method, frequency, owner, baseline and threshold or target connected to decisions.' },
  { id: 403, category: 4, text: 'Why does counting planted trees not prove improvement on its own?', options: ['Because trees do not matter', 'Because it measures activity, not survival, suitability or ecological function', 'Because there are always too many', 'Because trees cannot be counted'], correctIndex: 1, explanation: 'Activity must be linked to outcomes such as survival, diversity, structure, connectivity and restored functions over time.' },
  { id: 404, category: 4, text: 'What should accompany an environmental claim?', options: ['The colour green', 'Scope, period, method, data and limitations', 'A photograph only', 'An absolute statement'], correctIndex: 1, explanation: 'Responsible communication makes a claim verifiable and does not hide uncertainty, residual impacts or analytical boundaries.' },
  { id: 405, category: 4, text: 'What is a pressure indicator used for?', options: ['Measuring the cause or intensity of an impact', 'Describing reputation only', 'Replacing a baseline', 'Counting awards'], correctIndex: 0, explanation: 'Land occupied, noise, discharge or water use are pressures. They should be connected to the condition of ecological receptors.' },
  { id: 406, category: 4, text: 'If data are incomplete, which practice is appropriate?', options: ['Hide the gap', 'Document uncertainty, use prudent assumptions and improve the data', 'Invent a figure', 'Cancel all monitoring'], correctIndex: 1, explanation: 'Uncertainty does not prevent decisions, but it must be visible. Conservative assumptions and a data-improvement plan reduce false precision.' },
  { id: 407, category: 4, text: 'What is gained by combining remote-sensing and field data?', options: ['Spatial coverage and local validation', 'The removal of all uncertainty', 'Avoiding every site visit', 'Measuring costs only'], correctIndex: 0, explanation: 'Earth observation covers large areas and time series; fieldwork confirms species, condition and causes that an image may not distinguish.' },
  { id: 408, category: 4, text: 'Which question helps prioritise a nature-related issue?', options: ['Is the chart attractive?', 'What are the scale, sensitivity, dependency and level of influence?', 'How many colours does it use?', 'Can it be reduced to one word?'], correctIndex: 1, explanation: 'Prioritisation combines the significance of the impact or dependency, site sensitivity, organisational risk and the ability to influence outcomes.' },

  { id: 501, category: 5, text: 'A stain appears near a drain in an A400M maintenance area. What should happen first?', options: ['Wash it towards the drain', 'Stop the source, contain it and activate the incident procedure', 'Wait for it to evaporate', 'Cover it with soil'], correctIndex: 1, explanation: 'The priority is to protect people and the environment, stop the source and prevent the substance reaching soil or water. Notification, recovery and root-cause analysis follow.' },
  { id: 502, category: 5, text: 'A Eurofighter-related test coincides with a sensitive area and season for birds. Which response best follows the mitigation hierarchy?', options: ['Continue without changes', 'Review the route, timing or date to avoid the disturbance', 'Offset before assessing', 'Increase the number of flights'], correctIndex: 1, explanation: 'Operational planning may avoid a spatial or temporal overlap. Any remaining impact can then be assessed alongside additional measures and safety constraints.' },
  { id: 503, category: 5, text: 'When expanding a facility, which alternative should be assessed first?', options: ['The option occupying the most sensitive habitat', 'Reusing previously developed land and reducing new land take', 'The option most visible from the road', 'The option requiring more lighting'], correctIndex: 1, explanation: 'Reusing already altered land may avoid new habitat and soil loss, provided contamination, safety and feasibility are properly assessed.' },
  { id: 504, category: 5, text: 'How can wildlife management be reconciled with aviation safety?', options: ['Attract wildlife to runways', 'Design habitat measures through a combined risk assessment', 'Ignore bird movements', 'Remove all vegetation without assessment'], correctIndex: 1, explanation: 'Safety is the priority, but measures should reflect species, behaviour and local context so they do not create new attractants or unnecessary impacts.' },
  { id: 505, category: 5, text: 'For a purchase of wooden packaging, which evidence is most useful?', options: ['The packaging is painted green', 'Traceable origin and verified forest management', 'A verbal promise', 'The lowest weight with no further information'], correctIndex: 1, explanation: 'Traceability and verification help reduce deforestation and illegal-harvesting risks within the supply chain.' },
  { id: 506, category: 5, text: 'What can improve a mowing plan on industrial land?', options: ['Mowing every area at the same frequency all year', 'Adapting zones and timing to safety, fire risk and ecological cycles', 'Removing monitoring', 'Introducing invasive species'], correctIndex: 1, explanation: 'Differentiated management can preserve visibility and safety, reduce resource use and support habitat while avoiding sensitive periods where feasible.' },
  { id: 507, category: 5, text: 'What value can Earth observation add to environmental management?', options: ['It always replaces fieldwork', 'It helps detect change and prioritise verification', 'It removes the need for context', 'It only provides decorative imagery'], correctIndex: 1, explanation: 'Satellite time series can reveal changes in cover, moisture and land use. Interpretation still needs local knowledge and field validation.' },
  { id: 508, category: 5, text: 'After an environmental measure is implemented at a site, what closes the management cycle?', options: ['Publishing a photograph', 'Measuring results, comparing thresholds and correcting where necessary', 'Treating the action as complete', 'Renaming the project'], correctIndex: 1, explanation: 'Effectiveness must be demonstrated rather than assumed. Monitoring turns a one-off action into learning and continual improvement.' },
];

export function getRandomQuestion(category: number, usedIds: number[]): Question | null {
  const categoryQuestions = QUESTIONS.filter((question) => question.category === category);
  const available = categoryQuestions.filter((question) => !usedIds.includes(question.id));
  const pool = available.length > 0 ? available : categoryQuestions;
  return pool[Math.floor(Math.random() * pool.length)] ?? null;
}
